version: "2.1"
services:
  heimdall:
    build:
      context: .
      dockerfile: Dockerfile
#    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - /srv/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

